version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+pymysql://app_user:app_password@mysql:3306/app_db"
      POETRY_VIRTUALENVS_CREATE: "false"  # Poetry의 가상환경 비활성화

volumes:
  mysql_data:
